package com.government;

import com.government.rules.CentralGovernmentRules;
import com.government.rules.impl.*;

public class GovernmentExecutor {

    public static void main(String[] args) {


        CentralGovernmentRules karnataka = new KarnatakaImpl();
        karnataka.payTaxes();
        karnataka.followTrafficRules();
        karnataka.maintainPublicCleanliness();
        karnataka.respectNationalFlag();
        karnataka.followCyberLaws();
        karnataka.obeyCourtOrders();
        karnataka.registerBusinesses();
        karnataka.protectEnvironment();
        karnataka.followLaborLaws();
        karnataka.maintainPropertyRecords();
        karnataka.followEducationPolicies();
        karnataka.followHealthRegulations();
        karnataka.avoidCorruption();
        karnataka.followVotingRules();
        karnataka.respectWomenSafetyLaws();
        karnataka.protectWildlife();
        karnataka.followBankingRules();
        karnataka.maintainDigitalPrivacy();
        karnataka.followRoadSafety();
        karnataka.respectPublicProperty();
        karnataka.followConsumerProtection();
        karnataka.maintainTradeLicense();
        karnataka.followImportExportRules();
        karnataka.reportFinancialFraud();
        karnataka.followMunicipalRules();
        karnataka.maintainWaterConservation();
        karnataka.followFireSafetyRules();
        karnataka.respectHumanRights();
        karnataka.followIndustrialSafety();
        karnataka.maintainEnergyConservation();

        System.out.println("-----------------------------------------------------------------");


        CentralGovernmentRules tamilNadu = new TamilNaduImpl();
        tamilNadu.payTaxes();
        tamilNadu.followTrafficRules();
        tamilNadu.maintainPublicCleanliness();
        tamilNadu.respectNationalFlag();
        tamilNadu.followCyberLaws();
        tamilNadu.obeyCourtOrders();
        tamilNadu.registerBusinesses();
        tamilNadu.protectEnvironment();
        tamilNadu.followLaborLaws();
        tamilNadu.maintainPropertyRecords();
        tamilNadu.followEducationPolicies();
        tamilNadu.followHealthRegulations();
        tamilNadu.avoidCorruption();
        tamilNadu.followVotingRules();
        tamilNadu.respectWomenSafetyLaws();
        tamilNadu.protectWildlife();
        tamilNadu.followBankingRules();
        tamilNadu.maintainDigitalPrivacy();
        tamilNadu.followRoadSafety();
        tamilNadu.respectPublicProperty();
        tamilNadu.followConsumerProtection();
        tamilNadu.maintainTradeLicense();
        tamilNadu.followImportExportRules();
        tamilNadu.reportFinancialFraud();
        tamilNadu.followMunicipalRules();
        tamilNadu.maintainWaterConservation();
        tamilNadu.followFireSafetyRules();
        tamilNadu.respectHumanRights();
        tamilNadu.followIndustrialSafety();
        tamilNadu.maintainEnergyConservation();
        System.out.println("-----------------------------------------------------------------");

        CentralGovernmentRules kerala = new KeralaImpl();
        kerala.payTaxes();
        kerala.followTrafficRules();
        kerala.maintainPublicCleanliness();
        kerala.respectNationalFlag();
        kerala.followCyberLaws();
        kerala.obeyCourtOrders();
        kerala.registerBusinesses();
        kerala.protectEnvironment();
        kerala.followLaborLaws();
        kerala.maintainPropertyRecords();
        kerala.followEducationPolicies();
        kerala.followHealthRegulations();
        kerala.avoidCorruption();
        kerala.followVotingRules();
        kerala.respectWomenSafetyLaws();
        kerala.protectWildlife();
        kerala.followBankingRules();
        kerala.maintainDigitalPrivacy();
        kerala.followRoadSafety();
        kerala.respectPublicProperty();
        kerala.followConsumerProtection();
        kerala.maintainTradeLicense();
        kerala.followImportExportRules();
        kerala.reportFinancialFraud();
        kerala.followMunicipalRules();
        kerala.maintainWaterConservation();
        kerala.followFireSafetyRules();
        kerala.respectHumanRights();
        kerala.followIndustrialSafety();
        kerala.maintainEnergyConservation();
        System.out.println("-----------------------------------------------------------------");

        CentralGovernmentRules maharashtra = new MaharashtraImpl();
        maharashtra.payTaxes();
        maharashtra.followTrafficRules();
        maharashtra.maintainPublicCleanliness();
        maharashtra.respectNationalFlag();
        maharashtra.followCyberLaws();
        maharashtra.obeyCourtOrders();
        maharashtra.registerBusinesses();
        maharashtra.protectEnvironment();
        maharashtra.followLaborLaws();
        maharashtra.maintainPropertyRecords();
        maharashtra.followEducationPolicies();
        maharashtra.followHealthRegulations();
        maharashtra.avoidCorruption();
        maharashtra.followVotingRules();
        maharashtra.respectWomenSafetyLaws();
        maharashtra.protectWildlife();
        maharashtra.followBankingRules();
        maharashtra.maintainDigitalPrivacy();
        maharashtra.followRoadSafety();
        maharashtra.respectPublicProperty();
        maharashtra.followConsumerProtection();
        maharashtra.maintainTradeLicense();
        maharashtra.followImportExportRules();
        maharashtra.reportFinancialFraud();
        maharashtra.followMunicipalRules();
        maharashtra.maintainWaterConservation();
        maharashtra.followFireSafetyRules();
        maharashtra.respectHumanRights();
        maharashtra.followIndustrialSafety();
        maharashtra.maintainEnergyConservation();
        System.out.println("-----------------------------------------------------------------");

        CentralGovernmentRules telangana = new TelanganaImpl();
        telangana.payTaxes();
        telangana.followTrafficRules();
        telangana.maintainPublicCleanliness();
        telangana.respectNationalFlag();
        telangana.followCyberLaws();
        telangana.obeyCourtOrders();
        telangana.registerBusinesses();
        telangana.protectEnvironment();
        telangana.followLaborLaws();
        telangana.maintainPropertyRecords();
        telangana.followEducationPolicies();
        telangana.followHealthRegulations();
        telangana.avoidCorruption();
        telangana.followVotingRules();
        telangana.respectWomenSafetyLaws();
        telangana.protectWildlife();
        telangana.followBankingRules();
        telangana.maintainDigitalPrivacy();
        telangana.followRoadSafety();
        telangana.respectPublicProperty();
        telangana.followConsumerProtection();
        telangana.maintainTradeLicense();
        telangana.followImportExportRules();
        telangana.reportFinancialFraud();
        telangana.followMunicipalRules();
        telangana.maintainWaterConservation();
        telangana.followFireSafetyRules();
        telangana.respectHumanRights();
        telangana.followIndustrialSafety();
        telangana.maintainEnergyConservation();
        System.out.println("-----------------------------------------------------------------");

    }
}
